

project:
  type: book
  output-dir: docs
resources:
  - CNAME

book:
  title: "World Athletics Database as a CSV File"
  author: "Thomas Camminady"
  date: "7/04/2023"
  chapters:
    - index.qmd
    - contents/stats.ipynb
    - contents/analytics.qmd
    - contents/about_me.qmd
  twitter-card: true
  site-url: https://world-athletics-database.camminady.dev
execute:
  daemon: true

toc: true
number-sections: true


format:
  html:
    theme: mint
    page-layout: article
    code-fold: true
    code-line-numbers: true



