
project:
  type: website
  title: "world-athletics-database"
  output-dir: docs


toc: true
number-sections: true

format:
  html:
    page-layout: article
    code-fold: true
    code-line-numbers: true
    theme:
      - minty
