
project:
  type: website
  title: "world-athletics-database"
  output-dir: docs


toc: true
number-sections: true

format:
  html:
    page-layout: article
    code-fold: true
    code-line-numbers: true
    theme:
      - default



website:
  title: "World Athletics Database"
  open-graph: true

  navbar:
    right:
      - index.qmd
      - analytics.qmd
      - icon: github
        href: https://github.com/thomascamminady/world-athletics-database
