

project:
  type: book
  output-dir: docs

book:
  title: "world-athletics-database"
  author: "Thomas Camminady"
  date: "7/04/2023"
  chapters:
    - index.qmd
    - analytics.qmd
    - about_me.qmd
execute:
  daemon: true

toc: true
number-sections: true

format:
  html:
    theme: cosmo
    page-layout: article
    code-fold: true
    code-line-numbers: true



